<?php
// Public informed-consent endpoint — reached via a short link a nurse/admin
// sends to the client (generated by php-api/crm/consent-link.php). No CRM
// login: the random token is the credential, so every lookup is rate-limited
// and the token is only ever compared by its SHA-256 hash (never stored or
// logged in plaintext once issued).
//   GET  /php-api/consent-public.php?token=xxx   → booking + consent status
//   POST /php-api/consent-public.php?token=xxx   → record signed consent

require_once __DIR__ . '/crm/_crm.php';
handleCors();

$method = getMethod();
$token  = str_clean($_GET['token'] ?? '', 32);
if (!preg_match('/^[0-9A-Za-z]{8,32}$/', $token)) {
    jsonError('Link tidak valid', 400);
}
$tokenHash = hash('sha256', $token);
$ipHash    = getIpHash();
$db        = getDb();

if ($method === 'GET') {
    crmCheckPublicRateLimit($ipHash, 'LINK_VIEW', 10, 30);

    $l = $db->prepare(
        'SELECT id, booking_id FROM consent_links
         WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > NOW() LIMIT 1'
    );
    $l->execute([$tokenHash]);
    $link = $l->fetch();
    if (!$link) jsonError('Link tidak valid atau sudah kadaluarsa', 404);

    $b = $db->prepare(
        'SELECT b.id, b.booking_code_display, b.customer_name, b.crm_status, p.name AS product_name
         FROM bookings b JOIN products p ON p.id = b.product_id WHERE b.id = ? LIMIT 1'
    );
    $b->execute([$link['booking_id']]);
    $booking = $b->fetch();
    if (!$booking) jsonError('Booking tidak ditemukan', 404);

    $c = $db->prepare('SELECT patient_name_signed, agreed_at FROM consents WHERE booking_id = ? LIMIT 1');
    $c->execute([$link['booking_id']]);

    jsonSuccess(['booking' => $booking, 'consent' => $c->fetch() ?: null]);
}

if ($method === 'POST') {
    crmCheckPublicRateLimit($ipHash, 'LINK_SIGN', 10, 5);

    $l = $db->prepare(
        'SELECT id, booking_id FROM consent_links
         WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > NOW() LIMIT 1'
    );
    $l->execute([$tokenHash]);
    $link = $l->fetch();
    if (!$link) jsonError('Link tidak valid atau sudah kadaluarsa', 404);

    $bookingId = $link['booking_id'];
    $b = $db->prepare('SELECT customer_name, crm_status FROM bookings WHERE id = ? LIMIT 1');
    $b->execute([$bookingId]);
    $booking = $b->fetch();
    if (!$booking) jsonError('Booking tidak ditemukan', 404);

    // consents.booking_id is unique and agreed_at is always set on insert, so an
    // existing row — signed by the nurse in person or via an earlier link — means
    // this document is already final. Public link is create-only, never amends.
    $exists = $db->prepare('SELECT id FROM consents WHERE booking_id = ? LIMIT 1');
    $exists->execute([$bookingId]);
    if ($exists->fetch()) {
        jsonError('Consent ini sudah pernah ditandatangani sebelumnya', 409);
    }

    // Flow guard (mirrors consent.php): consent may only be taken after screening.
    if (crmStatusRank((string)$booking['crm_status']) < crmStatusRank('SCREENING_COMPLETED')) {
        jsonError('Pemeriksaan awal belum selesai. Silakan hubungi tim kami.', 409);
    }

    $body = getBodyJson();
    requireFields($body, ['patient_name_signed']);

    $nameSigned = str_clean($body['patient_name_signed'], 100);
    $sig        = !empty($body['signature_data']) ? encryptField((string)$body['signature_data']) : null;
    $lang       = in_array(($body['language'] ?? ''), ['en', 'id'], true) ? $body['language'] : null;
    $now        = date('Y-m-d H:i:s');

    $cid = generateId();
    $db->prepare(
        'INSERT INTO consents
         (id, booking_id, patient_name, patient_name_signed, signature_data_encrypted, consent_language, filled_by, consent_link_id, agreed_at, ip_address_hash, created_at)
         VALUES (?, ?, ?, ?, ?, ?, "CLIENT", ?, ?, ?, ?)'
    )->execute([$cid, $bookingId, $booking['customer_name'], $nameSigned, $sig, $lang, $link['id'], $now, $ipHash, $now]);

    $db->prepare('UPDATE consent_links SET used_at = NOW(3) WHERE id = ?')->execute([$link['id']]);

    crmAdvanceBookingStatus($db, $bookingId, 'CONSENT_SIGNED');
    crmAuditLog(null, 'CONSENT', 'SIGN_LINK', $bookingId, "Consent ditandatangani via link publik: $nameSigned" . ($lang ? " (bahasa: $lang)" : ''));

    jsonSuccess(['id' => $cid], 'Consent tersimpan. Terima kasih!');
}

jsonError('Method not allowed', 405);
