<?php
// Public treatment-feedback endpoint — reached via a short link a nurse/admin
// sends to the client after treatment (generated by php-api/crm/feedback-link.php).
// No CRM login: the random token is the credential, so every lookup is
// rate-limited and the token is only ever compared by its SHA-256 hash (never
// stored or logged in plaintext once issued).
//   GET  /php-api/feedback-public.php?token=xxx   → booking + feedback status
//   POST /php-api/feedback-public.php?token=xxx   → record feedback (rating + comment)

require_once __DIR__ . '/crm/_crm.php';
handleCors();

$method = getMethod();
$token  = str_clean($_GET['token'] ?? '', 32);
if (!preg_match('/^[0-9A-Za-z]{8,32}$/', $token)) {
    jsonError('Link tidak valid', 400);
}
$tokenHash = hash('sha256', $token);
$ipHash    = getIpHash();
$db        = getDb();

if ($method === 'GET') {
    crmCheckPublicRateLimit($ipHash, 'FEEDBACK_VIEW', 10, 30, 'FEEDBACK_LINK');

    $l = $db->prepare(
        'SELECT id, booking_id, viewed_at FROM feedback_links
         WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > NOW() LIMIT 1'
    );
    $l->execute([$tokenHash]);
    $link = $l->fetch();
    if (!$link) jsonError('Link tidak valid atau sudah kadaluarsa', 404);

    if (empty($link['viewed_at'])) {
        $db->prepare('UPDATE feedback_links SET viewed_at = NOW(3) WHERE id = ? AND viewed_at IS NULL')
           ->execute([$link['id']]);
    }

    // Batasi data yang ter-expose lewat link publik — hanya konteks minimal
    // yang dibutuhkan untuk menampilkan form, tidak ada phone/address/notes.
    $b = $db->prepare(
        'SELECT b.booking_code_display, b.customer_name, b.booking_date, p.name AS product_name
         FROM bookings b JOIN products p ON p.id = b.product_id WHERE b.id = ? LIMIT 1'
    );
    $b->execute([$link['booking_id']]);
    $booking = $b->fetch();
    if (!$booking) jsonError('Booking tidak ditemukan', 404);

    $f = $db->prepare('SELECT rating, submitted_at FROM feedbacks WHERE booking_id = ? LIMIT 1');
    $f->execute([$link['booking_id']]);
    $feedback = $f->fetch() ?: null;

    jsonSuccess(['booking' => $booking, 'feedback' => $feedback]);
}

if ($method === 'POST') {
    crmCheckPublicRateLimit($ipHash, 'FEEDBACK_SUBMIT', 10, 5, 'FEEDBACK_LINK');

    $l = $db->prepare(
        'SELECT id, booking_id FROM feedback_links
         WHERE token_hash = ? AND revoked_at IS NULL AND expires_at > NOW() LIMIT 1'
    );
    $l->execute([$tokenHash]);
    $link = $l->fetch();
    if (!$link) jsonError('Link tidak valid atau sudah kadaluarsa', 404);

    $bookingId = $link['booking_id'];

    // feedbacks.booking_id is unique — an existing row means this booking's
    // feedback is already final. Public link is create-only, never amends.
    $exists = $db->prepare('SELECT id FROM feedbacks WHERE booking_id = ? LIMIT 1');
    $exists->execute([$bookingId]);
    if ($exists->fetch()) {
        jsonError('Feedback untuk kunjungan ini sudah pernah diisi sebelumnya', 409);
    }

    $body = getBodyJson();
    requireFields($body, ['rating']);

    $rating = (int)$body['rating'];
    if ($rating < 1 || $rating > 5) jsonError('Rating harus antara 1 sampai 5', 422);

    $comment = !empty($body['comment']) ? str_clean($body['comment'], 2000) : null;
    $commentEncrypted = $comment !== null ? encryptField($comment) : null;

    $meetsExpectation = $body['meets_expectation'] ?? null;
    if (!in_array($meetsExpectation, ['YA', 'TIDAK', 'SEBAGIAN'], true)) {
        $meetsExpectation = null;
    }

    $now = date('Y-m-d H:i:s');
    $fid = generateId();
    $db->prepare(
        'INSERT INTO feedbacks
         (id, booking_id, feedback_link_id, rating, comment_encrypted, meets_expectation, submitted_at, ip_address_hash, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
    )->execute([$fid, $bookingId, $link['id'], $rating, $commentEncrypted, $meetsExpectation, $now, $ipHash, $now]);

    $db->prepare('UPDATE feedback_links SET used_at = NOW(3) WHERE id = ?')->execute([$link['id']]);

    // Feedback tidak memajukan crm_status — sifatnya suplemen, bukan bagian
    // dari alur klinis wajib seperti consent.
    $lowRatingTag = $rating <= 2 ? ' [LOW]' : '';
    crmAuditLog(null, 'FEEDBACK', 'SUBMIT', $bookingId, "Rating: {$rating}/5{$lowRatingTag}");

    jsonSuccess(['id' => $fid], 'Feedback tersimpan. Terima kasih!');
}

jsonError('Method not allowed', 405);
